-- Accounts: identity columns + the whole player document as JSONB (1:1 with the
-- SQLite `state` blob). The indexed columns are denormalised out of `state`
-- purely for lookup; `state` stays the source of truth for everything else.
CREATE TABLE IF NOT EXISTS accounts (
  account_id       BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10000001) PRIMARY KEY,
  open_id          TEXT UNIQUE,
  open_id_type     TEXT,
  nickname         TEXT,
  plat_id          BIGINT,
  region           TEXT,
  language         TEXT,
  device_id        TEXT,
  client_version   TEXT,
  level            INTEGER DEFAULT 1,
  clan_id          BIGINT DEFAULT 0,
  created_at       BIGINT,
  last_login_at    BIGINT,
  token            TEXT,
  token_created_at BIGINT,
  raw_login        JSONB,
  state            JSONB NOT NULL DEFAULT '{}'::jsonb
);

-- Bearer-token resolution on every authed request.
CREATE INDEX IF NOT EXISTS idx_accounts_token ON accounts (token);

-- Fuzzy nickname search — replaces the SQLite `LIKE COLLATE NOCASE` full scan.
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX IF NOT EXISTS idx_accounts_nickname_trgm
  ON accounts USING gin (lower(nickname) gin_trgm_ops);
