-- Promoted relational tables. Phase 1 creates the schema; the friend/clan/wallet
-- handlers move onto them incrementally (and Phase 3 settlement writes match_results).
-- Until then the accounts.state blob still holds these — these become canonical as
-- each domain is wired over, fixing the two-sided-friendship + scattered-clan bugs.

CREATE TABLE IF NOT EXISTS wallets (
  account_id BIGINT PRIMARY KEY REFERENCES accounts(account_id) ON DELETE CASCADE,
  coins      BIGINT NOT NULL DEFAULT 0,
  gems       BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS friendships (
  a          BIGINT NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
  b          BIGINT NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
  created_at BIGINT,
  PRIMARY KEY (a, b)
);
CREATE INDEX IF NOT EXISTS idx_friendships_b ON friendships (b);

CREATE TABLE IF NOT EXISTS friend_requests (
  target_id  BIGINT NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
  from_id    BIGINT NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
  created_at BIGINT,
  PRIMARY KEY (target_id, from_id)
);

CREATE TABLE IF NOT EXISTS clans (
  clan_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT UNIQUE,
  owner_id   BIGINT REFERENCES accounts(account_id) ON DELETE SET NULL,
  created_at BIGINT,
  meta       JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS clan_members (
  clan_id    BIGINT NOT NULL REFERENCES clans(clan_id) ON DELETE CASCADE,
  account_id BIGINT NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
  role       SMALLINT NOT NULL DEFAULT 0,
  joined_at  BIGINT,
  PRIMARY KEY (clan_id, account_id)
);
CREATE INDEX IF NOT EXISTS idx_clan_members_account ON clan_members (account_id);

-- Match settlement ledger = the idempotency guard. The (match_id, account_id) PK
-- makes at-least-once Stream delivery safe: settlement inserts here, and only a
-- fresh insert credits the wallet (Phase 3).
CREATE TABLE IF NOT EXISTS match_results (
  match_id    TEXT   NOT NULL,
  account_id  BIGINT NOT NULL REFERENCES accounts(account_id) ON DELETE CASCADE,
  coins       INTEGER NOT NULL DEFAULT 0,
  kills       INTEGER NOT NULL DEFAULT 0,
  deaths      INTEGER NOT NULL DEFAULT 0,
  win         BOOLEAN NOT NULL DEFAULT FALSE,
  rank_points INTEGER NOT NULL DEFAULT 0,
  xp          INTEGER NOT NULL DEFAULT 0,
  settled_at  BIGINT,
  PRIMARY KEY (match_id, account_id)
);
