// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: events.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- smoke test -----------------------------------------------------------
type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Nonce         int64                  `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Note          string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

func (x *Ping) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Ping) GetNonce() int64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *Ping) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type RosterSlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Team          uint32                 `protobuf:"varint,2,opt,name=team,proto3" json:"team,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RosterSlot) Reset() {
	*x = RosterSlot{}
	mi := &file_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RosterSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RosterSlot) ProtoMessage() {}

func (x *RosterSlot) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RosterSlot.ProtoReflect.Descriptor instead.
func (*RosterSlot) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{1}
}

func (x *RosterSlot) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *RosterSlot) GetTeam() uint32 {
	if x != nil {
		return x.Team
	}
	return 0
}

// "match.created" — matchmaker → match, main. Establishes the shared match-id
// keyspace the one-shot JWT never provided; L4 seeds the real roster/mode from it.
type MatchCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	ServerAddr    string                 `protobuf:"bytes,2,opt,name=server_addr,json=serverAddr,proto3" json:"server_addr,omitempty"` // instance the players were allocated to
	Roster        []*RosterSlot          `protobuf:"bytes,3,rep,name=roster,proto3" json:"roster,omitempty"`
	GameMode      uint32                 `protobuf:"varint,4,opt,name=game_mode,json=gameMode,proto3" json:"game_mode,omitempty"`
	MatchMode     uint32                 `protobuf:"varint,5,opt,name=match_mode,json=matchMode,proto3" json:"match_mode,omitempty"` // GameServerMatchMode (6 = CS ranking)
	MapId         string                 `protobuf:"bytes,6,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	City          string                 `protobuf:"bytes,7,opt,name=city,proto3" json:"city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchCreated) Reset() {
	*x = MatchCreated{}
	mi := &file_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchCreated) ProtoMessage() {}

func (x *MatchCreated) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchCreated.ProtoReflect.Descriptor instead.
func (*MatchCreated) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{2}
}

func (x *MatchCreated) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *MatchCreated) GetServerAddr() string {
	if x != nil {
		return x.ServerAddr
	}
	return ""
}

func (x *MatchCreated) GetRoster() []*RosterSlot {
	if x != nil {
		return x.Roster
	}
	return nil
}

func (x *MatchCreated) GetGameMode() uint32 {
	if x != nil {
		return x.GameMode
	}
	return 0
}

func (x *MatchCreated) GetMatchMode() uint32 {
	if x != nil {
		return x.MatchMode
	}
	return 0
}

func (x *MatchCreated) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

func (x *MatchCreated) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type PlayerResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Coins         int32                  `protobuf:"varint,2,opt,name=coins,proto3" json:"coins,omitempty"`
	Kills         int32                  `protobuf:"varint,3,opt,name=kills,proto3" json:"kills,omitempty"`
	Deaths        int32                  `protobuf:"varint,4,opt,name=deaths,proto3" json:"deaths,omitempty"`
	Win           bool                   `protobuf:"varint,5,opt,name=win,proto3" json:"win,omitempty"`
	RankPoints    int32                  `protobuf:"varint,6,opt,name=rank_points,json=rankPoints,proto3" json:"rank_points,omitempty"`
	Xp            int32                  `protobuf:"varint,7,opt,name=xp,proto3" json:"xp,omitempty"`
	Damage        int32                  `protobuf:"varint,8,opt,name=damage,proto3" json:"damage,omitempty"` // total damage dealt (scoreboard + MVP selection)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerResult) Reset() {
	*x = PlayerResult{}
	mi := &file_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerResult) ProtoMessage() {}

func (x *PlayerResult) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerResult.ProtoReflect.Descriptor instead.
func (*PlayerResult) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerResult) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *PlayerResult) GetCoins() int32 {
	if x != nil {
		return x.Coins
	}
	return 0
}

func (x *PlayerResult) GetKills() int32 {
	if x != nil {
		return x.Kills
	}
	return 0
}

func (x *PlayerResult) GetDeaths() int32 {
	if x != nil {
		return x.Deaths
	}
	return 0
}

func (x *PlayerResult) GetWin() bool {
	if x != nil {
		return x.Win
	}
	return false
}

func (x *PlayerResult) GetRankPoints() int32 {
	if x != nil {
		return x.RankPoints
	}
	return 0
}

func (x *PlayerResult) GetXp() int32 {
	if x != nil {
		return x.Xp
	}
	return 0
}

func (x *PlayerResult) GetDamage() int32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

// "match.result" — match → settlement worker, gateway. Settlement is idempotent
// on (match_id, account_id); redelivery must not double-credit.
type MatchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Players       []*PlayerResult        `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchResult) Reset() {
	*x = MatchResult{}
	mi := &file_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchResult) ProtoMessage() {}

func (x *MatchResult) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchResult.ProtoReflect.Descriptor instead.
func (*MatchResult) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{4}
}

func (x *MatchResult) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *MatchResult) GetPlayers() []*PlayerResult {
	if x != nil {
		return x.Players
	}
	return nil
}

// "match.ended" — match → matchmaker (capacity), main.
type MatchEnded struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	WinnerTeam    uint32                 `protobuf:"varint,2,opt,name=winner_team,json=winnerTeam,proto3" json:"winner_team,omitempty"`
	DurationMs    int64                  `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	EndType       uint32                 `protobuf:"varint,4,opt,name=end_type,json=endType,proto3" json:"end_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchEnded) Reset() {
	*x = MatchEnded{}
	mi := &file_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchEnded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchEnded) ProtoMessage() {}

func (x *MatchEnded) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchEnded.ProtoReflect.Descriptor instead.
func (*MatchEnded) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{5}
}

func (x *MatchEnded) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *MatchEnded) GetWinnerTeam() uint32 {
	if x != nil {
		return x.WinnerTeam
	}
	return 0
}

func (x *MatchEnded) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *MatchEnded) GetEndType() uint32 {
	if x != nil {
		return x.EndType
	}
	return 0
}

type WalletChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Coins         int64                  `protobuf:"varint,2,opt,name=coins,proto3" json:"coins,omitempty"`
	Gems          int64                  `protobuf:"varint,3,opt,name=gems,proto3" json:"gems,omitempty"`
	Delta         int64                  `protobuf:"varint,4,opt,name=delta,proto3" json:"delta,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletChanged) Reset() {
	*x = WalletChanged{}
	mi := &file_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletChanged) ProtoMessage() {}

func (x *WalletChanged) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletChanged.ProtoReflect.Descriptor instead.
func (*WalletChanged) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{6}
}

func (x *WalletChanged) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *WalletChanged) GetCoins() int64 {
	if x != nil {
		return x.Coins
	}
	return 0
}

func (x *WalletChanged) GetGems() int64 {
	if x != nil {
		return x.Gems
	}
	return 0
}

func (x *WalletChanged) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *WalletChanged) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type MailReceived struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TargetAccountId int64                  `protobuf:"varint,1,opt,name=target_account_id,json=targetAccountId,proto3" json:"target_account_id,omitempty"`
	MailId          string                 `protobuf:"bytes,2,opt,name=mail_id,json=mailId,proto3" json:"mail_id,omitempty"`
	Kind            string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Attachments     []byte                 `protobuf:"bytes,4,opt,name=attachments,proto3" json:"attachments,omitempty"` // serialized mail body (opaque here)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MailReceived) Reset() {
	*x = MailReceived{}
	mi := &file_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailReceived) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailReceived) ProtoMessage() {}

func (x *MailReceived) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailReceived.ProtoReflect.Descriptor instead.
func (*MailReceived) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{7}
}

func (x *MailReceived) GetTargetAccountId() int64 {
	if x != nil {
		return x.TargetAccountId
	}
	return 0
}

func (x *MailReceived) GetMailId() string {
	if x != nil {
		return x.MailId
	}
	return ""
}

func (x *MailReceived) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *MailReceived) GetAttachments() []byte {
	if x != nil {
		return x.Attachments
	}
	return nil
}

type FriendRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TargetAccountId int64                  `protobuf:"varint,1,opt,name=target_account_id,json=targetAccountId,proto3" json:"target_account_id,omitempty"`
	AdderAccountId  int64                  `protobuf:"varint,2,opt,name=adder_account_id,json=adderAccountId,proto3" json:"adder_account_id,omitempty"`
	AdderNickname   string                 `protobuf:"bytes,3,opt,name=adder_nickname,json=adderNickname,proto3" json:"adder_nickname,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FriendRequest) Reset() {
	*x = FriendRequest{}
	mi := &file_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequest) ProtoMessage() {}

func (x *FriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequest.ProtoReflect.Descriptor instead.
func (*FriendRequest) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{8}
}

func (x *FriendRequest) GetTargetAccountId() int64 {
	if x != nil {
		return x.TargetAccountId
	}
	return 0
}

func (x *FriendRequest) GetAdderAccountId() int64 {
	if x != nil {
		return x.AdderAccountId
	}
	return 0
}

func (x *FriendRequest) GetAdderNickname() string {
	if x != nil {
		return x.AdderNickname
	}
	return ""
}

type FriendConfirmed struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AdderAccountId     int64                  `protobuf:"varint,1,opt,name=adder_account_id,json=adderAccountId,proto3" json:"adder_account_id,omitempty"`
	ConfirmerAccountId int64                  `protobuf:"varint,2,opt,name=confirmer_account_id,json=confirmerAccountId,proto3" json:"confirmer_account_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FriendConfirmed) Reset() {
	*x = FriendConfirmed{}
	mi := &file_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendConfirmed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendConfirmed) ProtoMessage() {}

func (x *FriendConfirmed) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendConfirmed.ProtoReflect.Descriptor instead.
func (*FriendConfirmed) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{9}
}

func (x *FriendConfirmed) GetAdderAccountId() int64 {
	if x != nil {
		return x.AdderAccountId
	}
	return 0
}

func (x *FriendConfirmed) GetConfirmerAccountId() int64 {
	if x != nil {
		return x.ConfirmerAccountId
	}
	return 0
}

type ClanUpdated struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ClanId            int64                  `protobuf:"varint,1,opt,name=clan_id,json=clanId,proto3" json:"clan_id,omitempty"`
	Change            string                 `protobuf:"bytes,2,opt,name=change,proto3" json:"change,omitempty"` // created | member_joined | member_left | dismissed | renamed
	AffectedAccountId int64                  `protobuf:"varint,3,opt,name=affected_account_id,json=affectedAccountId,proto3" json:"affected_account_id,omitempty"`
	MemberIds         []int64                `protobuf:"varint,4,rep,packed,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClanUpdated) Reset() {
	*x = ClanUpdated{}
	mi := &file_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClanUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClanUpdated) ProtoMessage() {}

func (x *ClanUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClanUpdated.ProtoReflect.Descriptor instead.
func (*ClanUpdated) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{10}
}

func (x *ClanUpdated) GetClanId() int64 {
	if x != nil {
		return x.ClanId
	}
	return 0
}

func (x *ClanUpdated) GetChange() string {
	if x != nil {
		return x.Change
	}
	return ""
}

func (x *ClanUpdated) GetAffectedAccountId() int64 {
	if x != nil {
		return x.AffectedAccountId
	}
	return 0
}

func (x *ClanUpdated) GetMemberIds() []int64 {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

type PresenceChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"` // online | offline | in-match
	Node          string                 `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
	TsUnixMs      int64                  `protobuf:"varint,4,opt,name=ts_unix_ms,json=tsUnixMs,proto3" json:"ts_unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceChanged) Reset() {
	*x = PresenceChanged{}
	mi := &file_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceChanged) ProtoMessage() {}

func (x *PresenceChanged) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceChanged.ProtoReflect.Descriptor instead.
func (*PresenceChanged) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{11}
}

func (x *PresenceChanged) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *PresenceChanged) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *PresenceChanged) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *PresenceChanged) GetTsUnixMs() int64 {
	if x != nil {
		return x.TsUnixMs
	}
	return 0
}

type SessionRevoke struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionRevoke) Reset() {
	*x = SessionRevoke{}
	mi := &file_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRevoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRevoke) ProtoMessage() {}

func (x *SessionRevoke) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRevoke.ProtoReflect.Descriptor instead.
func (*SessionRevoke) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{12}
}

func (x *SessionRevoke) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *SessionRevoke) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// "gw.push" — any layer → the gateway holding target_account_id relays this to the
// client as a MessageNotify{protocol, cmd, content}. Ephemeral PubSub: dropped if the
// target isn't connected (the DB stays the durable source of truth). `content` is a
// pre-encoded TCP proto, so the gateway is a DUMB relay with no per-message knowledge.
type GatewayPush struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TargetAccountId int64                  `protobuf:"varint,1,opt,name=target_account_id,json=targetAccountId,proto3" json:"target_account_id,omitempty"`
	Protocol        uint32                 `protobuf:"varint,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Cmd             uint32                 `protobuf:"varint,3,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Content         []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GatewayPush) Reset() {
	*x = GatewayPush{}
	mi := &file_events_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayPush) ProtoMessage() {}

func (x *GatewayPush) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayPush.ProtoReflect.Descriptor instead.
func (*GatewayPush) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{13}
}

func (x *GatewayPush) GetTargetAccountId() int64 {
	if x != nil {
		return x.TargetAccountId
	}
	return 0
}

func (x *GatewayPush) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *GatewayPush) GetCmd() uint32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *GatewayPush) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type PlayerUpdated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Version       uint32                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	ChangedFields []string               `protobuf:"bytes,3,rep,name=changed_fields,json=changedFields,proto3" json:"changed_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerUpdated) Reset() {
	*x = PlayerUpdated{}
	mi := &file_events_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerUpdated) ProtoMessage() {}

func (x *PlayerUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerUpdated.ProtoReflect.Descriptor instead.
func (*PlayerUpdated) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{14}
}

func (x *PlayerUpdated) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *PlayerUpdated) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PlayerUpdated) GetChangedFields() []string {
	if x != nil {
		return x.ChangedFields
	}
	return nil
}

var File_events_proto protoreflect.FileDescriptor

const file_events_proto_rawDesc = "" +
	"\n" +
	"\fevents.proto\x12\x03bus\"D\n" +
	"\x04Ping\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\x03R\x05nonce\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\"?\n" +
	"\n" +
	"RosterSlot\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12\x12\n" +
	"\x04team\x18\x02 \x01(\rR\x04team\"\xda\x01\n" +
	"\fMatchCreated\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12\x1f\n" +
	"\vserver_addr\x18\x02 \x01(\tR\n" +
	"serverAddr\x12'\n" +
	"\x06roster\x18\x03 \x03(\v2\x0f.bus.RosterSlotR\x06roster\x12\x1b\n" +
	"\tgame_mode\x18\x04 \x01(\rR\bgameMode\x12\x1d\n" +
	"\n" +
	"match_mode\x18\x05 \x01(\rR\tmatchMode\x12\x15\n" +
	"\x06map_id\x18\x06 \x01(\tR\x05mapId\x12\x12\n" +
	"\x04city\x18\a \x01(\tR\x04city\"\xcc\x01\n" +
	"\fPlayerResult\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12\x14\n" +
	"\x05coins\x18\x02 \x01(\x05R\x05coins\x12\x14\n" +
	"\x05kills\x18\x03 \x01(\x05R\x05kills\x12\x16\n" +
	"\x06deaths\x18\x04 \x01(\x05R\x06deaths\x12\x10\n" +
	"\x03win\x18\x05 \x01(\bR\x03win\x12\x1f\n" +
	"\vrank_points\x18\x06 \x01(\x05R\n" +
	"rankPoints\x12\x0e\n" +
	"\x02xp\x18\a \x01(\x05R\x02xp\x12\x16\n" +
	"\x06damage\x18\b \x01(\x05R\x06damage\"U\n" +
	"\vMatchResult\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12+\n" +
	"\aplayers\x18\x02 \x03(\v2\x11.bus.PlayerResultR\aplayers\"\x84\x01\n" +
	"\n" +
	"MatchEnded\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12\x1f\n" +
	"\vwinner_team\x18\x02 \x01(\rR\n" +
	"winnerTeam\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x03R\n" +
	"durationMs\x12\x19\n" +
	"\bend_type\x18\x04 \x01(\rR\aendType\"\x86\x01\n" +
	"\rWalletChanged\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12\x14\n" +
	"\x05coins\x18\x02 \x01(\x03R\x05coins\x12\x12\n" +
	"\x04gems\x18\x03 \x01(\x03R\x04gems\x12\x14\n" +
	"\x05delta\x18\x04 \x01(\x03R\x05delta\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"\x89\x01\n" +
	"\fMailReceived\x12*\n" +
	"\x11target_account_id\x18\x01 \x01(\x03R\x0ftargetAccountId\x12\x17\n" +
	"\amail_id\x18\x02 \x01(\tR\x06mailId\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12 \n" +
	"\vattachments\x18\x04 \x01(\fR\vattachments\"\x8c\x01\n" +
	"\rFriendRequest\x12*\n" +
	"\x11target_account_id\x18\x01 \x01(\x03R\x0ftargetAccountId\x12(\n" +
	"\x10adder_account_id\x18\x02 \x01(\x03R\x0eadderAccountId\x12%\n" +
	"\x0eadder_nickname\x18\x03 \x01(\tR\radderNickname\"m\n" +
	"\x0fFriendConfirmed\x12(\n" +
	"\x10adder_account_id\x18\x01 \x01(\x03R\x0eadderAccountId\x120\n" +
	"\x14confirmer_account_id\x18\x02 \x01(\x03R\x12confirmerAccountId\"\x8d\x01\n" +
	"\vClanUpdated\x12\x17\n" +
	"\aclan_id\x18\x01 \x01(\x03R\x06clanId\x12\x16\n" +
	"\x06change\x18\x02 \x01(\tR\x06change\x12.\n" +
	"\x13affected_account_id\x18\x03 \x01(\x03R\x11affectedAccountId\x12\x1d\n" +
	"\n" +
	"member_ids\x18\x04 \x03(\x03R\tmemberIds\"x\n" +
	"\x0fPresenceChanged\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x12\n" +
	"\x04node\x18\x03 \x01(\tR\x04node\x12\x1c\n" +
	"\n" +
	"ts_unix_ms\x18\x04 \x01(\x03R\btsUnixMs\"F\n" +
	"\rSessionRevoke\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x81\x01\n" +
	"\vGatewayPush\x12*\n" +
	"\x11target_account_id\x18\x01 \x01(\x03R\x0ftargetAccountId\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\rR\bprotocol\x12\x10\n" +
	"\x03cmd\x18\x03 \x01(\rR\x03cmd\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\"o\n" +
	"\rPlayerUpdated\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\x12%\n" +
	"\x0echanged_fields\x18\x03 \x03(\tR\rchangedFieldsB\"Z libmadoka/match-server/bus/pb;pbb\x06proto3"

var (
	file_events_proto_rawDescOnce sync.Once
	file_events_proto_rawDescData []byte
)

func file_events_proto_rawDescGZIP() []byte {
	file_events_proto_rawDescOnce.Do(func() {
		file_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)))
	})
	return file_events_proto_rawDescData
}

var file_events_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_events_proto_goTypes = []any{
	(*Ping)(nil),            // 0: bus.Ping
	(*RosterSlot)(nil),      // 1: bus.RosterSlot
	(*MatchCreated)(nil),    // 2: bus.MatchCreated
	(*PlayerResult)(nil),    // 3: bus.PlayerResult
	(*MatchResult)(nil),     // 4: bus.MatchResult
	(*MatchEnded)(nil),      // 5: bus.MatchEnded
	(*WalletChanged)(nil),   // 6: bus.WalletChanged
	(*MailReceived)(nil),    // 7: bus.MailReceived
	(*FriendRequest)(nil),   // 8: bus.FriendRequest
	(*FriendConfirmed)(nil), // 9: bus.FriendConfirmed
	(*ClanUpdated)(nil),     // 10: bus.ClanUpdated
	(*PresenceChanged)(nil), // 11: bus.PresenceChanged
	(*SessionRevoke)(nil),   // 12: bus.SessionRevoke
	(*GatewayPush)(nil),     // 13: bus.GatewayPush
	(*PlayerUpdated)(nil),   // 14: bus.PlayerUpdated
}
var file_events_proto_depIdxs = []int32{
	1, // 0: bus.MatchCreated.roster:type_name -> bus.RosterSlot
	3, // 1: bus.MatchResult.players:type_name -> bus.PlayerResult
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_events_proto_init() }
func file_events_proto_init() {
	if File_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_proto_goTypes,
		DependencyIndexes: file_events_proto_depIdxs,
		MessageInfos:      file_events_proto_msgTypes,
	}.Build()
	File_events_proto = out.File
	file_events_proto_goTypes = nil
	file_events_proto_depIdxs = nil
}
