'use strict';

// One-shot data migration: copy every account from the SQLite accounts.db into
// Postgres (schema-first — run `npm run migrate` beforehand). Re-runnable: rows
// upsert by account_id, and the identity sequence is advanced past the migrated
// ids afterwards (explicit-id inserts don't advance it). Run pre-cutover while
// SQLite is still the source of truth.
//   DATABASE_URL=... npm run migrate-data
require('dotenv').config();

const path = require('path');

// Full accounts column set (matches migrations/001 + the SQLite schema 1:1).
const COLUMNS = [
  'account_id', 'open_id', 'open_id_type', 'nickname', 'plat_id', 'region',
  'language', 'device_id', 'client_version', 'level', 'clan_id', 'created_at',
  'last_login_at', 'token', 'token_created_at', 'raw_login', 'state'
];
const JSON_COLUMNS = new Set(['raw_login', 'state']);

// Normalise a SQLite JSON/TEXT value for a JSONB column. `def` is used when the
// value is missing/corrupt (state must never be null; raw_login may be).
function jsonText(value, def) {
  if (value == null || value === '') return def;
  if (typeof value === 'object') return JSON.stringify(value);
  try {
    JSON.parse(value);
    return value;
  } catch (err) {
    return def;
  }
}

// Migrate all accounts from a better-sqlite3 handle into Postgres via pgClient
// (a pg Client/Pool). Injectable so it can be tested against pg-mem.
async function migrateData(sqlite, pgClient, log = console.log) {
  const rows = sqlite.prepare('SELECT * FROM accounts').all();
  log(`[migrate-data] read ${rows.length} accounts`);

  const placeholders = COLUMNS
    .map((c, i) => (JSON_COLUMNS.has(c) ? `$${i + 1}::jsonb` : `$${i + 1}`))
    .join(', ');
  const updates = COLUMNS.slice(1).map((c) => `${c} = EXCLUDED.${c}`).join(', ');
  const sql = `INSERT INTO accounts (${COLUMNS.join(', ')}) VALUES (${placeholders})
               ON CONFLICT (account_id) DO UPDATE SET ${updates}`;

  let n = 0;
  for (const r of rows) {
    const values = COLUMNS.map((c) => {
      if (c === 'state') return jsonText(r.state, '{}');
      if (c === 'raw_login') return jsonText(r.raw_login, null);
      return r[c];
    });
    await pgClient.query(sql, values);
    n += 1;
  }

  // Advance the identity sequence past the migrated ids so new accounts don't
  // collide (GENERATED BY DEFAULT does not advance the sequence on explicit ids).
  try {
    await pgClient.query(
      `SELECT setval(pg_get_serial_sequence('accounts', 'account_id'),
              GREATEST((SELECT COALESCE(MAX(account_id), 10000000) FROM accounts), 10000000))`
    );
  } catch (err) {
    log(`[migrate-data] sequence reset skipped: ${err.message}`);
  }

  log(`[migrate-data] upserted ${n} accounts`);
  return n;
}

async function main() {
  const config = require('../../config/default');
  const Database = require('better-sqlite3');
  const { Pool } = require('pg');

  const dbFile = (config.db && config.db.file) || path.join(__dirname, '..', '..', 'data', 'accounts.db');
  const pgUrl = process.env.DATABASE_URL || (config.postgres && config.postgres.url);
  if (!pgUrl) {
    console.error('[migrate-data] DATABASE_URL (or config.postgres.url) is not set');
    process.exit(1);
  }

  const sqlite = new Database(dbFile, { readonly: true });
  const pool = new Pool({ connectionString: pgUrl });
  const client = await pool.connect();
  try {
    await client.query('BEGIN');
    await migrateData(sqlite, client);
    await client.query('COMMIT');
    console.log('[migrate-data] committed');
  } catch (err) {
    await client.query('ROLLBACK');
    console.error(`[migrate-data] failed (rolled back): ${err.message}`);
    process.exitCode = 1;
  } finally {
    client.release();
    await pool.end();
    sqlite.close();
  }
}

if (require.main === module) main();

module.exports = { migrateData };
